name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Check code format
        run: ./mill mill.scalalib.scalafmt/checkFormatAll
      - name: Compile
        run: ./mill '__.compile'
      - name: Test
        run: ./mill '__.test'
