name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check code format
        uses: jrouly/scalafmt-native-action@v1
        with:
          version: "3.7.12"
          arguments: "-c .scalafmt.conf --test"
      - uses: jodersky/setup-mill@v0.3.0
        with:
          mill-version: 0.11.4
      - name: Compile
        run: mill '__.compile'
      - name: Test
        run: mill '__.test'
