name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set version
        run: sed -i "s/publishVersion = \"\(.*\)\"/publishVersion = \"\1-$(echo ${GITHUB_SHA} | cut -c1-8)-SNAPSHOT\"/g" build.mill
      - name: Publish
        shell: bash
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.OSS_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.OSS_PASSWORD }}
        run: |
          ./mill mill.javalib.SonatypeCentralPublishModule/ --publishArtifacts __.publishArtifacts
